#!/bin/sh
set -e

[[ -d build ]] && rm -rf build
mkdir -p build/floppy1 dist

pushd build
cmake ..
CC=gcc make clean all
cp ../emptyfat12.img orange.iso

sudo mount -o loop,fat=12 orange.img floppy1
cp KRNLDR floppy/KRNLDR.SYS || (echo "Failed to copy Loader" && exit 1)
cp KRNL floppy/KRNL.SYS || (echo "Failed to copy Kernel" && exit 1)
sudo umount floppy1
dd bs=512 count=1 if=Stage1 of=orange.img conv=notrunc
popd

mv build/orange.img  dist/orange-$(date +"%Y%m%d-%H%M%S").img
rm -rf build
echo "DONE!"