#!/bin/sh
MODULES="libc kernel"

export MAKE=${MAKE:-make}
export HOST=${HOST:-$(./default-host)}

export AR=${HOST}-ar
export AS=${HOST}-as
CC=${HOST}-gcc
LD=${HOST}-ld
export ARCH=${ARCH:-$(./target-triplet-to-arch ${HOST})}
export PREFIX=/usr
export EXEC_PREFIX=$PREFIX
export BOOTDIR=/boot
export LIBDIR=$EXEC_PREFIX/lib
export INCLUDEDIR=$PREFIX/include

export CFLAGS='-O2 -g'
export CPPFLAGS=''

# Configure the cross-compiler to use the desired system root.
if [[ "x$ARCH" == "xx86_64" ]]; then
	CC="$CC -mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2"
fi

CC="$CC --sysroot=$PWD/../dist"
LD="$LD --sysroot=$PWD/../dist"

# Work around that the -elf gcc targets doesn't have a system include directory
# because configure received --without-headers rather than --with-sysroot.
if echo "$HOST" | grep -Eq -- '-elf($|-)'; then
	export CC="$CC -isystem=$INCLUDEDIR"
	export LD="$LD -isystem=$INCLUDEDIR"
fi
export CC
export LD
export NASM=$(which nasm)